### PR TITLE
Add Urho3D assert macros.

### PR DESCRIPTION
**Pull request by eugeneko**
@rokups @gleblebedev I want to introduce this as alternative to logging errors and/or `assert`. What do you think?

### CODE REVIEW

**Comment by rokups** [comment]
Sure why not

**Comment by gleblebedev** [comment]
Should it at least log in release?

**Comment by eugeneko** [comment]
It works identically in both debug and release unless disabled

Вс, 19 дек. 2021 г. в 12:16, gleblebedev ***@***.***>:

**Comment by gleblebedev** [comment]
I was confused by DEBUG in the macro name....

**Pull request merged**
