### PR TITLE
Drop tool build when crosscompiling

### PR DESCRIPTION
**Pull request by rokups**
This change reworks CI to use `URHO3D_HOST_SDK` and artifact download to gain access to tools when needed. This paves the way for removing `MINI_URHO`.

Notable changes/things to be aware of:
+ Now we always upload artifacts for release builds (required by CI)
+ When crosscompiling now users have to set ~~`-DURHO3D_HOST_SDK=...`~~ `-DURHO3D_SDK=...` to installed desktop build for the host. So far, only required when `URHO3D_PACKAGING` or `URHO3D_CSHARP` is `ON`.
+ We **can not** set CMake build dir of of host build to ~~`URHO3D_HOST_SDK`~~ `URHO3D_SDK`, but it could be allowed by generating fake `share/CMake/Urho3D.cmake` that exports needed targets.
+ In order to avoid target name collision we install CMake targets twice. ~~Once as normal, to `share/CMake` and once within internal namespace to `share/CMake/Private`. This is kind of dumb, but works so lets move on..~~ Library targets are installed to `share/CMake/Urho3D.cmake` and tool targets are installed to `share/CMake/Urho3DTools.cmake`. This allows crosscompiled builds to consume tools built for the host since we do not build tools when crosscompiling.
+ Due to these changes, desktop builds (Windows/Linux/MacOS) build first. Crosscompiled targets (UWP/iOS/Android/web) depend on desktop builds and trigger only after all desktop builds of required OS are done.

### CODE REVIEW

**Comment by eugeneko** [comment]
>  So far, only required when URHO3D_PACKAGING or URHO3D_CSHARP is ON.

Why C#?

**Comment by rokups** [comment]
Because SWIG.

**Comment by eugeneko** [comment]
But *why* does SWIG need native SDK?

**Comment by rokups** [comment]
It's a tool, just like PackageTool. You can't build swig for Android and
run it on your host machine 👀

**Comment by eugeneko** [comment]
Yeah, but Package Tool needs entire engine to be built, and swigtool is just a thirdparty that depends on nothing (?).
So it feels weird that we must do entire separate build for sake of one tool.

It is kinda moot point because we pretty much *require* `URHO3D_PACKAGING` for every sane build... but still.

**Comment by rokups** [comment]
Point is to remove all those hacks that build tools using host toolchain while crosscompiling. We are simplifying build system. I would say getting rid of `MINI_URHO` is even a lesser benefit here. Also, we don't actually require `URHO3D_PACKAGING`. All crosscompiled platforms can embed dirs with files, using packaging methods of that particular toolchain. So desktop SDK is even optional, unless we chose to do actual packaging (which we do in builds of samples, but that is just our choice).

**Comment by rokups** [comment]
Im done ironing out issues. There were some changes which are reflected in the first message.

**Comment by rokups** [comment]
I added `SDKTools.cmake`+some fluff which serves similar purpose like installed SDK - including this file defines variables with paths to swig/PackageTool executables if they were available. These files are available in cmake cache dir as well so now we do not need to install SDK and tools can be used from another cmake build cache dir.

**Comment by rokups** [comment]
@eugeneko this PR is as ready as it will ever be. Docs are here: https://github.com/rbfx/rbfx-docs/pull/1.

**Comment by rokups** [comment]
@eugeneko, approval? 😁

**Review by eugeneko — APPROVED** [review]
I have no clue what half of this means. I may or may not come to you when I rebase Diligent branch on top of that.

**Pull request merged**
