### PR TITLE
Components may be created when engine is not fully initialized

### PR DESCRIPTION
**Pull request by gleblebedev**

### CODE REVIEW

**Comment by rokups** [comment]
What is the usecase? I really don't like this... If anything, this check should be an asset. Loading stuff too early is very unsafe and who knows what can happen

**Comment by eugeneko** [comment]
So, if DPad adapter is created too early, it just silently stops working partially?..

**Comment by gleblebedev** [comment]
@rokups @eugeneko the problem is in c# wrapper. It tries to create an instance of the object during type registration for some reason and this code is executed early in the engine initialization. @rokups do you remember why?

**Comment by rokups** [comment]
Right... This is a very unfortunate case, because we need an object instance in order to determine the default value of the attribute. If not for default values, instance would not be required. Maybe a correct solution here would be delaying reflection registration to after object has initialized. Maybe by firing an event between `Setup()` and `Start()`.

**Pull request closed without merging**
