### PR TITLE
Added support for using a user defined transport

### PR DESCRIPTION
**Pull request by plumgames**
Adding this because I need to integrate a third party transport in user code. 

I have a follow up PR related to transports which expands on this but I'm trying to keep the PR sizes to a minimum for now 😅

### CODE REVIEW

**Review by rokups — APPROVED** [review]
Thanks for this one 🫡

**Comment by eugeneko** [comment]
Is this tested with some real custom transport?
The change is okay per se, but it looks suspiciously simple.
I would like to be sure that this is indeed enough to have custom transport.

**Comment by plumgames** [comment]
> Is this tested with some real custom transport? The change is okay per se, but it looks suspiciously simple. I would like to be sure that this is indeed enough to have custom transport.

I am using it with a custom transport in my own project but it's not in state where I can share it at this time.

I do have another transport that can be used to validate this change, with some effort required though. 

I implemented an 'App' transport for clients and a server running in the same process (part of my dev workflow, very useful for many reasons). I added this transport at the engine level since I planned to PR it eventually but you could rip it out, put in user code and then set that as a custom transport and validate that it works.

[AppServer.h](https://github.com/plumgames/rbfx/blob/a81705304db4b46dbd40dc828438bcdb5c90e179/Source/Urho3D/Network/Transport/App/AppServer.h)
[AppServer.cpp](https://github.com/plumgames/rbfx/blob/a81705304db4b46dbd40dc828438bcdb5c90e179/Source/Urho3D/Network/Transport/App/AppServer.cpp)
[AppConnection.h](https://github.com/plumgames/rbfx/blob/a81705304db4b46dbd40dc828438bcdb5c90e179/Source/Urho3D/Network/Transport/App/AppConnection.h)
[AppConnection.cpp](https://github.com/plumgames/rbfx/blob/a81705304db4b46dbd40dc828438bcdb5c90e179/Source/Urho3D/Network/Transport/App/AppConnection.cpp)

**Comment by rokups** [comment]
@eugeneko it is indeed this simple. This was the whole point of network reqork, which enabled networking in web builds

**Comment by plumgames** [comment]
@rokups 

The web build fails but not sure why this happens, I remember repro'ing this locally when running a web build for the first time with this branch. The second time the build is run the error goes away. 

Seems like a build/linker ordering issue related to how `datachannel-wasm` differs from `datachannel-static` in CMakeLists.

```
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcDeleteDataChannel
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcDeleteDataChannel
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSetUserPointer
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSetOpenCallback
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSetErrorCallback
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSetMessageCallback
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSetBufferedAmountLowCallback
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcGetDataChannelLabel
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcDeleteDataChannel
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSendMessage
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcGetBufferedAmount
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: getDataChannelOrdered
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: getDataChannelMaxPacketLifeTime
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: getDataChannelMaxRetransmits
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSetBufferedAmountLowThreshold
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSendMessage
wasm-ld: error: lib/libdatachannel-wasm.a(datachannel.cpp.o): undefined symbol: rtcSendMessage
wasm-ld: error: lib/libdatachannel-wasm.a(peerconnection.cpp.o): undefined symbol: rtcCreatePeerConnection
wasm-ld: error: lib/libdatachannel-wasm.a(peerconnection.cpp.o): undefined symbol: rtcSetUserPointer
wasm-ld: error: lib/libdatachannel-wasm.a(peerconnection.cpp.o): undefined symbol: rtcSetDataChannelCallback
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
```

**Comment by plumgames** [comment]
@eugeneko what do I need to do to get this merged? Do you want me to add a usage in example in the `AdvancedNetworking` sample?

**Comment by rokups** [comment]
Thank you for reminding us of this. If @eugeneko does not come up with any complaints ill merge this in coming days.

**Comment by eugeneko** [comment]
@rokups, @plumgames
This code crashes our samples because these functions are used and never initialized xD

I made a few tweaks, if the new code looks okay for you @plumgames I will merge it.

**Comment by eugeneko** [comment]
Wait, I see now. It does not link on Web if I initialize it this way.
And "fixing" in the commit above didn't fix the problem, it just converted link time issue into realtime crash.

**Comment by eugeneko** [comment]
Okay, this is green. @plumgames does it look good for you?

**Comment by plumgames** [comment]
Yep, tested these latest changes on web/standalone 👍 

> Wait, I see now. It does not link on Web if I initialize it this way.

I remember this one had me stumped for hours and I gave up, hence that hacky workaround commit

> I don't see any usecase in having Player in web builds by default so I removed it.

When I tried to make a web build with -DURHO3D_PLAYER=OFF I get a linker error because my sample-project derived project still needs to link PlayerLibrary. I ended up doing this to work around it, not sure why the ci build wouldn't encounter the same issue: https://github.com/plumgames/rbfx/commit/c202cee2a6e29813e10e62ee4d4f8f2d747b1eb3

The web build is a lot faster now for me, especially in release mode since it doesn't have to run wasm-opt on the Player exe.

**Comment by eugeneko** [comment]
@plumgames in your builds, you can use `URHO3D_NO_EDITOR_PLAYER_EXE=ON` with `URHO3D_PLAYER=ON` to get library without executable. This use case is the reason why we have these two defines.

**Pull request merged**
