### PR TITLE
Terrain RGBA read, GTLFImporter Name Correcting

### PR DESCRIPTION
**Pull request by qwertyu131**
I added control to GLTF Importer name extraction.
I have the map heights read as floats. For this reading method, it will be enough to set the float to the rgba value.

### CODE REVIEW

**Comment by gleblebedev** [comment]
Would be nice to have 1 feature per PR. This way it may be easier to track them down,  cherry-pick, roll back, etc.

**Comment by eugeneko** [comment]
@qwertyu131 Can you please explain the function of importer changes, on real world example? I struggle to understand it.

**Comment by qwertyu131** [comment]
Json -> "images":[{"name":"images_name.png","bufferView":0,"mimeType":"image/png"}
Even though the json data has name, uri_name was being set.
In the outputs, the image name parts were like texture_%d.png. It will be a problem for those who want to use the names of the files.

**Comment by eugeneko** [comment]
I merged GLTF part manually.

I don't want to merge terrain part because it is basically your personal file format support. Storing floats bit-by-bit in the image is way too specialized and there are no public tools that can generate such images.

**Pull request closed without merging**
