### PR TITLE
Fixing ImGui InputText string buffer

### PR DESCRIPTION
**Pull request by gleblebedev**

### CODE REVIEW

**Comment by eugeneko** [comment]
Can you explain how it works? I would like to get a bit of understanding in this area, and I have no clue what your code does.

**Comment by rokups** [comment]
> Can you explain how it works? I would like to get a bit of understanding in this area, and I have no clue what your code does.

`public static bool InputText(string label, ref Span<byte> buffer, ImGuiInputTextFlags flags = 0)` is a public C# API which takes C#-native `ref Span<byte>` which wrapped function can modify. It takes all inputs and convert then to C types, so in case of span it becomes a buffer pointer + length. Then this function calls a C wrapper function `CSharp_ImGuiNet_InputText`, which to C# is exposed by a function declaration `private static extern bool ImGui_InputText(string label, byte* buffer, int bufferSize, int flags);`. `CSharp_ImGuiNet_InputText` is a dumb wrapper around `ImGui::InputText()`, merely passing its inputs. Even though `ImGui::InputText` parameters are C-compatible, we can not call it directly due to C++ name mangling, so we use that wrapper to get a predictable exported name.

**Review by rokups — APPROVED** [review]

**Comment by rokups** [comment]
Right. `Span<byte>` would point to a byte array of static size on C# side

**Comment by gleblebedev** [comment]
> Right. `Span<byte>` would point to a byte array of static size on C# side

Not only byte array. You can cast spans if needed, also you can get Span from Memory<>, memory mapped file, unmanaged memory allocated via Marshal.AllocHGlobal, etc. Basically Span<> is a pointer + buffer size that has few safety checks on top of that.

**Pull request merged**
