### PR TITLE
Add chromatic aberration post processing shader

### PR DESCRIPTION
**Pull request by niansa**
For those who wonder about a valid usecase: I actually need this for in-game cam screens ;-)

### CODE REVIEW

**Comment by niansa** [comment]
Still working on variable intensity

**Comment by niansa** [comment]
Done, should be alright now.

**Comment by eugeneko** [comment]
Okay, one technical question.
Since you probably didn't write the shader yourself, I need some kind of confirmation that used code is compatible with MIT license of rbfx repo.

**Comment by niansa** [comment]
This is the link to the source shader:
https://www.shadertoy.com/view/XssGz8

The first two lines (sorry, can't copy them on mobile) should answer your question.

**Comment by niansa** [comment]
Also: the shadertoy links only link to common algorithm implementations. So these shouldn't be a problem either.

**Comment by eugeneko** [comment]
Can you please keep this stuff in the branch?
I was going to use this feature as an example of post process plug-in, but
the engine does not support plug-in resources yet.

**Pull request closed without merging**
