### PR TITLE
Set high dpi to true to make engine to draw the entire window

### PR DESCRIPTION
**Pull request by KatekovAnton**
Screen Shot 2021-12-15 at 22 44 07

Without this engine only draws a quarter of the window. So "false" value is broken on mac. I suggest to set it to true in order to let mac users to try SamplesManager without troubles.

### CODE REVIEW

**Comment by KatekovAnton** [comment]
bump

**Comment by eugeneko** [comment]
@KatekovAnton did you check Editor?
Maybe we need to change here as well?
https://github.com/rbfx/rbfx/blob/5afd551e6844e959a604e637dc3b6f328172d6f7/Source/Tools/Editor/Editor.cpp#L151

**Comment by KatekovAnton** [comment]
I changed `EP_HIGH_DPI` to true and Editor.cpp have value of `true` too. So it is aligned now, I can use the editor without changes. I think current editor is ok.

**Comment by eugeneko** [comment]
Sorry, I referenced wrong line.
Does Editor work when URHO3D_SYSTEMUI_VIEWPORTS is off? It uses `false` in this case:
https://github.com/rbfx/rbfx/blob/5afd551e6844e959a604e637dc3b6f328172d6f7/Source/Tools/Editor/Editor.cpp#L154

**Pull request merged**
