### PR TITLE
Water tweaks

### PR DESCRIPTION
**Pull request by gleblebedev**

### CODE REVIEW

**Comment by gleblebedev** [comment]
IMG_20220813_165144

**Comment by eugeneko** [comment]
image
It's too unstable to be in the showcase: saturation increase affects lighting, which looks very weird

**Comment by gleblebedev** [comment]
> image It's too unstable to be in the showcase: saturation increase affects lighting, which looks very weird

It should take roughness into account. 

Maybe 1.2 for saturation is too much. Maybe it should be a pow argument instead? The Anthem didn't tell what function they used for saturation, just "desaturate" shader node with negative argument.

**Comment by eugeneko** [comment]
Maybe it should be applied to the gbuffer, not the final output color?

**Comment by gleblebedev** [comment]
> Maybe it should be applied to the gbuffer, not the final output color?

Makes sense. But this would require deeper integration to the render pipeline... Does it worth it?

**Pull request closed without merging**
